import {
  // Storage & warehousing
  Warehouse,
  Boxes,
  Box,
  Package,
  PackageCheck,
  PackageOpen,
  PackagePlus,
  PackageMinus,
  PackageX,
  PackageSearch,
  Container,
  Archive,
  ArchiveRestore,
  Layers,

  // Temperature & climate
  Snowflake,
  ThermometerSnowflake,
  Thermometer,
  ThermometerSun,
  Wind,
  Sun,
  Cloud,
  CloudRain,
  CloudSnow,
  Droplet,
  Droplets,

  // Security
  ShieldCheck,
  Shield,
  ShieldAlert,
  Lock,
  LockKeyhole,
  Unlock,
  Key,
  Eye,
  Camera,
  Fingerprint,
  ScanFace,

  // Transportation & logistics
  Truck,
  Ship,
  Plane,
  Train,
  Bus,
  Car,
  Forklift,
  Anchor,
  Navigation,
  Compass,
  MapPin,
  Map,
  Globe,
  Route,
  Fuel,

  // Power & utilities
  PlugZap,
  Plug,
  BatteryCharging,
  Battery,
  Zap,
  Power,
  Gauge,
  Cpu,

  // Doors & access
  DoorOpen,
  DoorClosed,
  LogIn,
  LogOut,

  // Documents & records
  ClipboardList,
  ClipboardCheck,
  ClipboardX,
  Clipboard,
  FileText,
  FileCheck,
  Database,
  BarChart,
  LineChart,
  PieChart,
  TrendingUp,
  TrendingDown,
  Calculator,

  // Time & scheduling
  CalendarClock,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Clock,
  Timer,
  History,
  AlarmClock,

  // Tools & industry
  Wrench,
  Hammer,
  Cog,
  Settings,
  HardHat,
  Ruler,
  Factory,
  Building2,
  Building,
  Home,
  Landmark,
  Recycle,
  Leaf,
  TreePine,

  // Food & industries served
  Utensils,
  UtensilsCrossed,
  Fish,
  Beef,
  Egg,
  Apple,
  Carrot,
  Coffee,
  Wine,
  Salad,
  Pizza,
  Soup,
  Milk,
  Hotel,
  Store,
  ShoppingCart,
  ShoppingBag,

  // People & business
  Users,
  User,
  UserCheck,
  UsersRound,
  Briefcase,
  Handshake,

  // Finance
  DollarSign,
  CreditCard,
  Wallet,
  Banknote,
  Receipt,
  PiggyBank,

  // Status & feedback
  CheckCircle2,
  CheckCircle,
  XCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  Star,
  Award,
  Medal,
  Trophy,
  Target,
  Flag,
  BadgeCheck,

  // Communication
  Phone,
  PhoneCall,
  Mail,
  MessageCircle,
  MessageSquare,
  Send,

  // Navigation & UI
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ChevronRight,
  ChevronLeft,
  ExternalLink,
  Link,
  CheckSquare,
  Square,
  Circle,
  Hexagon,

  type LucideIcon,
} from "lucide-react";

/**
 * Controlled icon map. Content editors select icons by key from Sanity;
 * we never dynamically import icons from arbitrary user input. Keep this
 * object's keys in sync with ICON_KEYS in
 * sanity/schemaTypes/objects/editableIcon.ts — every key here must also
 * appear there (and vice versa) or the Studio dropdown and the rendered
 * icon will silently disagree.
 */
export const iconMap = {
  // Storage & warehousing
  warehouse: Warehouse,
  boxes: Boxes,
  box: Box,
  package: Package,
  packageCheck: PackageCheck,
  packageOpen: PackageOpen,
  packagePlus: PackagePlus,
  packageMinus: PackageMinus,
  packageX: PackageX,
  packageSearch: PackageSearch,
  container: Container,
  archive: Archive,
  archiveRestore: ArchiveRestore,
  layers: Layers,

  // Temperature & climate
  snowflake: Snowflake,
  thermometerSnowflake: ThermometerSnowflake,
  thermometer: Thermometer,
  thermometerSun: ThermometerSun,
  wind: Wind,
  sun: Sun,
  cloud: Cloud,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  droplet: Droplet,
  droplets: Droplets,

  // Security
  shieldCheck: ShieldCheck,
  shield: Shield,
  shieldAlert: ShieldAlert,
  lock: Lock,
  lockKeyhole: LockKeyhole,
  unlock: Unlock,
  key: Key,
  eye: Eye,
  camera: Camera,
  fingerprint: Fingerprint,
  scanFace: ScanFace,

  // Transportation & logistics
  truck: Truck,
  ship: Ship,
  plane: Plane,
  train: Train,
  bus: Bus,
  car: Car,
  forklift: Forklift,
  anchor: Anchor,
  navigation: Navigation,
  compass: Compass,
  mapPin: MapPin,
  map: Map,
  globe: Globe,
  route: Route,
  fuel: Fuel,

  // Power & utilities
  plugZap: PlugZap,
  plug: Plug,
  batteryCharging: BatteryCharging,
  battery: Battery,
  zap: Zap,
  power: Power,
  gauge: Gauge,
  cpu: Cpu,

  // Doors & access
  doorOpen: DoorOpen,
  doorClosed: DoorClosed,
  logIn: LogIn,
  logOut: LogOut,

  // Documents & records
  clipboardList: ClipboardList,
  clipboardCheck: ClipboardCheck,
  clipboardX: ClipboardX,
  clipboard: Clipboard,
  fileText: FileText,
  fileCheck: FileCheck,
  database: Database,
  barChart: BarChart,
  lineChart: LineChart,
  pieChart: PieChart,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  calculator: Calculator,

  // Time & scheduling
  calendarClock: CalendarClock,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  calendarDays: CalendarDays,
  clock: Clock,
  timer: Timer,
  history: History,
  alarmClock: AlarmClock,

  // Tools & industry
  wrench: Wrench,
  hammer: Hammer,
  cog: Cog,
  settings: Settings,
  hardHat: HardHat,
  ruler: Ruler,
  factory: Factory,
  building2: Building2,
  building: Building,
  home: Home,
  landmark: Landmark,
  recycle: Recycle,
  leaf: Leaf,
  treePine: TreePine,

  // Food & industries served
  utensils: Utensils,
  utensilsCrossed: UtensilsCrossed,
  fish: Fish,
  beef: Beef,
  egg: Egg,
  apple: Apple,
  carrot: Carrot,
  coffee: Coffee,
  wine: Wine,
  salad: Salad,
  pizza: Pizza,
  soup: Soup,
  milk: Milk,
  hotel: Hotel,
  store: Store,
  shoppingCart: ShoppingCart,
  shoppingBag: ShoppingBag,

  // People & business
  users: Users,
  user: User,
  userCheck: UserCheck,
  usersRound: UsersRound,
  briefcase: Briefcase,
  handshake: Handshake,

  // Finance
  dollarSign: DollarSign,
  creditCard: CreditCard,
  wallet: Wallet,
  banknote: Banknote,
  receipt: Receipt,
  piggyBank: PiggyBank,

  // Status & feedback
  checkCircle2: CheckCircle2,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  info: Info,
  helpCircle: HelpCircle,
  star: Star,
  award: Award,
  medal: Medal,
  trophy: Trophy,
  target: Target,
  flag: Flag,
  badgeCheck: BadgeCheck,

  // Communication
  phone: Phone,
  phoneCall: PhoneCall,
  mail: Mail,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  send: Send,

  // Navigation & UI
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  externalLink: ExternalLink,
  link: Link,
  checkSquare: CheckSquare,
  square: Square,
  circle: Circle,
  hexagon: Hexagon,
} as const satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof iconMap;
