import {
  Warehouse,
  Snowflake,
  PackageCheck,
  Container,
  ShieldCheck,
  Truck,
  ThermometerSnowflake,
  Database,
  PlugZap,
  DoorOpen,
  ClipboardList,
  CalendarClock,
  ClipboardCheck,
  Boxes,
  Building2,
  Ruler,
  DoorClosed,
  Factory,
  Recycle,
  BatteryCharging,
  Camera,
  Utensils,
  Hotel,
  ShoppingCart,
  Building,
  Fish,
  MapPin,
  Phone,
  Mail,
  ArrowRight,
  type LucideIcon,
} from "lucide-react";

/**
 * Controlled icon map. Content editors select icons by key from Sanity;
 * we never dynamically import icons from arbitrary user input.
 */
export const iconMap = {
  warehouse: Warehouse,
  snowflake: Snowflake,
  packageCheck: PackageCheck,
  container: Container,
  shieldCheck: ShieldCheck,
  truck: Truck,
  thermometerSnowflake: ThermometerSnowflake,
  database: Database,
  plugZap: PlugZap,
  doorOpen: DoorOpen,
  clipboardList: ClipboardList,
  calendarClock: CalendarClock,
  clipboardCheck: ClipboardCheck,
  boxes: Boxes,
  building2: Building2,
  ruler: Ruler,
  doorClosed: DoorClosed,
  factory: Factory,
  recycle: Recycle,
  batteryCharging: BatteryCharging,
  camera: Camera,
  utensils: Utensils,
  hotel: Hotel,
  shoppingCart: ShoppingCart,
  building: Building,
  fish: Fish,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  arrowRight: ArrowRight,
} as const satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof iconMap;
